# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/111XyPfIUKhXoVHwXvxXsxleeSbvpHgq_
"""

import torch
import torch.nn.functional as F
import numpy as np
import torchvision.transforms as transforms



device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

if torch.cuda.is_available() :
  print("cuda")
else:
  print("cpu")

