# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/111XyPfIUKhXoVHwXvxXsxleeSbvpHgq_
"""

print("hello")